sonar.projectKey=python-operational-metrics-api
sonar.projectName=Python Operational Metrics API
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.exclusions=**/__init__.py
